---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webserver-ns
  name: nginx-web-deploy
  labels:
    app: app-nginx-web
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "50%"
      maxUnavailable: "50%"
  selector:
    matchLabels:
      app: app-nginx-web
  template:
    metadata:
      labels:
        app: app-nginx-web
    spec:
      containers:
      - name: nginx-web-container
        image: <<image:tag>>
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: webserver-ns
  name: nginx-web-service
  labels:
    run: nginx-web-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: app-nginx-web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: webserver-ns
  name: ingress-sa
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-alias: "web.k8s-4.sa"
spec:
  rules:
    - host: app.k8s-18.sa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-web-service
                port:
                  number: 80
